### ISSUE TITLE
fallback to ip tools when ethtool details are missing

### ISSUE THREAD

**Issue by norg** [DCSO/ethflux#5]
There are some drivers/cards that miss some stats via ethtool but provide them via `ip -s link`, for example the `rx_dropped` value.

So one possibility would be to use those as fallback

**Comment by satta** [comment]
Not sure whether ethflux is the correct place to do things like that...? I'm a fan of the old principle of having a tool do one thing and do it right ;)
I'd say if it's not in the `ethtool` output, the user would need a different way of getting that value, e.g. using a different script in another `[[inputs.exec]]` section which sends the other value to another measurement. Any ideas?

**Comment by norg** [comment]
After more thoughts, I agree it won't be a proper solution.
